model_class = "OfficeDocumentAnnotationModel"

schema_id = "file/office
schema_version = "1.0.0"

[[dependencies]]
type = "media_type"
include = [
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation"
]

[options]
# The office model currently requires no runtime configuration options.